[package]
name = "waystone"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
serde = {version = "1.0", features = ["derive"]}
serde_yml = "0.0.12"

[dev-dependencies]
tempfile = "3"
