name: Check PR title
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main]

jobs:
  check_title:
    runs-on: ubuntu-latest
    steps:
      - uses: ytanikin/PRConventionalCommits@1.3.0
        with:
          task_types: '["build","feat","fix","docs","test","ci","style","refactor","perf","chore"]'
          add_label: false
